import { useEffect, useState } from "react";
import { api } from "../api/client";

const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export default function Planner() {
  const [subjects, setSubjects] = useState([]);
  const [schedule, setSchedule] = useState(null);
  const [hoursPerDay, setHoursPerDay] = useState({
    0: 2,
    1: 4,
    2: 4,
    3: 4,
    4: 4,
    5: 3,
    6: 2,
  });
  const [form, setForm] = useState({
    dayOfWeek: 1,
    startTime: "09:00",
    endTime: "10:00",
    subject: "",
    priority: 3,
    label: "",
  });
  const [msg, setMsg] = useState("");

  async function load() {
    const [subs, sch] = await Promise.all([api("/api/subjects"), api("/api/schedule")]);
    setSubjects(subs);
    setSchedule(sch);
    if (!form.subject && subs[0]?._id) setForm((f) => ({ ...f, subject: subs[0]._id }));
  }

  useEffect(() => {
    load().catch((e) => setMsg(e.message));
  }, []);

  async function addBlock(e) {
    e.preventDefault();
    setMsg("");
    const items = [...(schedule?.items || [])];
    items.push({
      dayOfWeek: Number(form.dayOfWeek),
      startTime: form.startTime,
      endTime: form.endTime,
      subject: form.subject || null,
      label: form.label,
      priority: Number(form.priority),
      isAutoGenerated: false,
    });
    const updated = await api("/api/schedule", { method: "PUT", body: JSON.stringify({ items }) });
    setSchedule(updated);
    setMsg("Block added.");
  }

  async function autoGenerate() {
    setMsg("");
    const updated = await api("/api/schedule/generate", {
      method: "POST",
      body: JSON.stringify({ hoursPerDay }),
    });
    setSchedule(updated);
    setMsg("Schedule generated from availability and performance.");
  }

  async function removeItem(id) {
    const items = (schedule?.items || []).filter((i) => i._id !== id);
    const updated = await api("/api/schedule", { method: "PUT", body: JSON.stringify({ items }) });
    setSchedule(updated);
  }

  const grouped = days.map((d, day) => ({
    day,
    label: d,
    items: (schedule?.items || []).filter((i) => i.dayOfWeek === day).sort((a, b) => a.startTime.localeCompare(b.startTime)),
  }));

  return (
    <div className="space-y-8">
      <header>
        <h1 className="font-display text-3xl font-bold text-ink">Smart planner</h1>
        <p className="text-ink-muted mt-1">
          Build your timetable or auto-generate from hours per day, subjects, and difficulty.
        </p>
      </header>

      {msg && (
        <div className="text-sm text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-4 py-2 rounded-lg">
          {msg}
        </div>
      )}

      <section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-6 bg-surface">
        <h2 className="font-semibold text-ink mb-4">Auto-generate</h2>
        <p className="text-sm text-ink-muted mb-4">
          Set available hours per weekday (0–12). Prioritizes harder subjects and weaker scores.
        </p>
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-3 mb-4">
          {days.map((d, i) => (
            <label key={d} className="text-xs">
              <span className="text-ink-muted">{d}</span>
              <input
                type="number"
                min={0}
                max={12}
                className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-1.5 text-sm"
                value={hoursPerDay[i]}
                onChange={(e) =>
                  setHoursPerDay((h) => ({ ...h, [i]: Number(e.target.value) }))
                }
              />
            </label>
          ))}
        </div>
        <button
          type="button"
          onClick={() => autoGenerate().catch((e) => setMsg(e.message))}
          className="px-4 py-2 rounded-lg bg-accent text-white text-sm font-medium hover:bg-indigo-600"
        >
          Generate schedule
        </button>
      </section>

      <section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-6 bg-surface">
        <h2 className="font-semibold text-ink mb-4">Add manual block</h2>
        <form onSubmit={addBlock} className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 items-end">
          <label className="text-xs">
            <span className="text-ink-muted">Day</span>
            <select
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.dayOfWeek}
              onChange={(e) => setForm((f) => ({ ...f, dayOfWeek: e.target.value }))}
            >
              {days.map((d, i) => (
                <option key={d} value={i}>
                  {d}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs">
            <span className="text-ink-muted">Start</span>
            <input
              type="time"
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.startTime}
              onChange={(e) => setForm((f) => ({ ...f, startTime: e.target.value }))}
            />
          </label>
          <label className="text-xs">
            <span className="text-ink-muted">End</span>
            <input
              type="time"
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.endTime}
              onChange={(e) => setForm((f) => ({ ...f, endTime: e.target.value }))}
            />
          </label>
          <label className="text-xs">
            <span className="text-ink-muted">Subject</span>
            <select
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.subject}
              onChange={(e) => setForm((f) => ({ ...f, subject: e.target.value }))}
            >
              <option value="">—</option>
              {subjects.map((s) => (
                <option key={s._id} value={s._id}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs">
            <span className="text-ink-muted">Priority (1–5)</span>
            <input
              type="number"
              min={1}
              max={5}
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.priority}
              onChange={(e) => setForm((f) => ({ ...f, priority: e.target.value }))}
            />
          </label>
          <label className="text-xs sm:col-span-2">
            <span className="text-ink-muted">Label (optional)</span>
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 px-2 py-2 text-sm"
              value={form.label}
              onChange={(e) => setForm((f) => ({ ...f, label: e.target.value }))}
            />
          </label>
          <button
            type="submit"
            className="py-2 rounded-lg bg-slate-800 dark:bg-slate-200 text-white dark:text-slate-900 text-sm font-medium"
          >
            Add block
          </button>
        </form>
      </section>

      <section className="space-y-6">
        <h2 className="font-display font-semibold text-xl text-ink">Weekly view</h2>
        {grouped.map(({ day, label, items }) => (
          <div
            key={day}
            className="rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden"
          >
            <div className="bg-surface-muted px-4 py-2 font-medium text-sm text-ink">{label}</div>
            <ul className="divide-y divide-slate-200 dark:divide-slate-700">
              {items.length === 0 ? (
                <li className="px-4 py-3 text-sm text-ink-muted">No blocks</li>
              ) : (
                items.map((item) => (
                  <li
                    key={item._id}
                    className="px-4 py-3 flex flex-wrap items-center justify-between gap-2 text-sm"
                  >
                    <span>
                      {item.startTime}–{item.endTime} · {item.subject?.name || item.label || "Session"}
                      {item.isAutoGenerated && (
                        <span className="ml-2 text-xs text-ink-muted">auto</span>
                      )}
                    </span>
                    <span className="flex items-center gap-2">
                      <span className="text-ink-muted">P{item.priority}</span>
                      <button
                        type="button"
                        onClick={() => removeItem(item._id).catch((e) => setMsg(e.message))}
                        className="text-rose-500 text-xs hover:underline"
                      >
                        Remove
                      </button>
                    </span>
                  </li>
                ))
              )}
            </ul>
          </div>
        ))}
      </section>
    </div>
  );
}
