const mongoose = require("mongoose");

const scheduleItemSchema = new mongoose.Schema(
  {
    dayOfWeek: { type: Number, required: true, min: 0, max: 6 },
    startTime: { type: String, required: true },
    endTime: { type: String, required: true },
    subject: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subject",
      default: null,
    },
    label: { type: String, default: "" },
    priority: { type: Number, min: 1, max: 5, default: 3 },
    isAutoGenerated: { type: Boolean, default: false },
  },
  { _id: true }
);

const scheduleSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true },
    items: [scheduleItemSchema],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Schedule", scheduleSchema);
