const difficultyWeight = { easy: 1, medium: 2, hard: 3 };

/**
 * @param {object} params
 * @param {Record<number, number>} params.hoursPerDay - dayOfWeek -> available hours (0-6, Sun=0)
 * @param {Array<{ _id: any, name: string, difficulty: string, avgScore?: number }>} params.subjects
 */
function generateScheduleItems({ hoursPerDay, subjects }) {
  const items = [];
  if (!subjects?.length) return items;

  const ranked = [...subjects].sort((a, b) => {
    const da = difficultyWeight[a.difficulty] || 2;
    const db = difficultyWeight[b.difficulty] || 2;
    const sa = a.avgScore ?? 50;
    const sb = b.avgScore ?? 50;
    const pa = da * 2 + (100 - sa) / 25;
    const pb = db * 2 + (100 - sb) / 25;
    return pb - pa;
  });

  const blockMinutes = 60;
  let subjectIndex = 0;

  for (let day = 0; day <= 6; day++) {
    const hours = Math.min(Math.max(Number(hoursPerDay[day]) || 0, 0), 12);
    const blocks = Math.floor((hours * 60) / blockMinutes);
    let startHour = 9;
    for (let b = 0; b < blocks; b++) {
      const sub = ranked[subjectIndex % ranked.length];
      subjectIndex++;
      const startM = startHour * 60;
      const endM = startM + blockMinutes;
      const startTime = `${String(Math.floor(startM / 60)).padStart(2, "0")}:${String(startM % 60).padStart(2, "0")}`;
      const endTime = `${String(Math.floor(endM / 60)).padStart(2, "0")}:${String(endM % 60).padStart(2, "0")}`;
      const priority = sub.difficulty === "hard" ? 5 : sub.difficulty === "medium" ? 3 : 2;
      items.push({
        dayOfWeek: day,
        startTime,
        endTime,
        subject: sub._id,
        label: sub.name,
        priority,
        isAutoGenerated: true,
      });
      startHour += 1;
      if (startHour > 20) startHour = 9;
    }
  }

  return items;
}

module.exports = { generateScheduleItems };
